// fake_ssids.cpp
// A list of 1000 unique, funny fake WiFi SSIDs for a skit / prank hotspot list.
// Each SSID is guaranteed to be <= 32 characters (the max SSID length).

const char* fakeSSIDs[] = {
    // ---- Group 1: SSIDs 1-100 ----
    "Hotspot Is Way Too Extra", "Hotspot Is Playing Favorites", "Sketchy Signal", "Funky Firewall", "Network Needs A Vacation",
    "Router Has Zero Chill Left", "Ratty Ethernet", "Network Runs On Spite", "Network Just Woke Up Grumpy", "Access Point Is Having A Moment",
    "Password Is Way Too Extra", "Funky LAN", "Hotspot Needs More Coffee", "Router On Vacation Forever", "Hotspot Runs On Spite",
    "Lazy Hotspot", "WiFi Needs A Hug Please", "Quirky Access Point", "Firewall Woke Up Like This", "Moody Connection",
    "Lazy Network", "Sneezy Password", "Zesty LAN", "Dorky Network", "Sneezy Firewall",
    "Noisy Antenna", "LAN Is Way Too Extra", "WiFi Zero Effort", "Router Monsters Inc Scare", "WPA2 And Emotionally Unavailable",
    "Modem Is In Its Feelings", "Router Rickroll Zone", "Router Needs Its Space", "Router Is Feeling Petty", "Router Of Theseus",
    "Router Full Of Secrets", "Dorky LAN", "Router Rumble In Jungle", "Antenna Has Left The Group", "The Password Is No",
    "Quirky Broadband", "Hotspot Needs A Hug Please", "Router Is Extra Today", "Hotspot Is In Its Feelings", "Fancy Antenna",
    "Definitely Not WiFi", "WiFi Witness Protection", "Router Full Of Chaos", "Salty LAN", "LAN Judges Your Life",
    "WiFi Is On A Diet", "Router That Cried Wolf", "LAN Has Trust Issues Now", "WiFi Currently Ghosting", "Broadband Needs A Hug Please",
    "Sketchy Ethernet", "Sneezy WiFi", "Access Point Needs Its Space", "Ethernet Refuses To Behave", "Cocky Modem",
    "WiFi Runs On Spite", "Chatty Bandwidth", "Router Is In Its Feelings", "Megabyte My Style", "WiFi Says Maybe Later",
    "Signal Is Plotting Something", "The Wireless Witness Stand", "Sneezy Ethernet", "Quirky Router", "Salty WiFi",
    "Wonky Password", "Spicy Signal", "Sassy Bandwidth", "Wireless Wanderlust Only", "Classy Broadband",
    "Clumsy Ethernet", "Antenna Is Currently Sulking", "Modem Is Playing Favorites", "Router Brave Heart Scot", "Mom Said No WiFi",
    "Wonky Antenna", "Cocky Network", "Sketchy Access Point", "Network Is Feeling Petty", "Bossy Signal",
    "Classy Signal", "Firewall Is Way Too Extra", "LAN Solo", "Bossy Network", "Terabyte Terror Zone",
    "Salty Router", "Firewall Is Plotting Something", "The Router Formerly Known", "Router Frozen Let It Go", "Firewall Is Out Of Office",
    "Nosy Access Point", "Connection Needs A Vacation", "Bandwidth Is Low Key Judging", "Bandwidth Refuses To Behave", "Firewall Runs On Spite",

    // ---- Group 2: SSIDs 101-200 ----
    "Snappy Antenna", "Cranky Access Point", "WiFi Is Having A Moment", "Signal Needs More Coffee", "Hotspot Refuses To Behave",
    "Router Jackson", "Spicy Connection", "Router Ruckus Downtown", "Lazy WiFi", "Jumpy Broadband",
    "Jumpy Modem", "Bandwidth Woke Up Like This", "Clumsy Signal", "Moody LAN", "Loading Trust Fund",
    "Nosy Broadband", "The Cache Me Outside", "Bandwidth Bonanza Tonight", "Access Point Is Way Too Extra", "Jumpy Signal",
    "Hotspot Is Living Its Truth", "WiFi Very Suspicious", "Two Girls One Router", "Fancy Router", "Corny Broadband",
    "This Is Not Free WiFi", "Cocky Password", "Sneaky Broadband", "Cranky Router", "Data Cap Meltdown",
    "WiFi Is Plotting Something", "The Router That Could", "Router Refuses To Behave", "Signal Has Zero Chill Left", "Loading Unresolved Feelings",
    "Cranky Signal", "Sneaky Connection", "Petty LAN", "Jumpy Ethernet", "Broadband Woke Up Like This",
    "Sneaky Modem", "Firewall Is Currently Sulking", "LAN Needs A Snack Break", "The LAN Before Time", "Sneaky Firewall",
    "Dorky Password", "Connection Runs On Spite", "Fancy Firewall", "Feisty Access Point", "The Wifi Is A Lie",
    "Dorky Access Point", "Sudo Give Me WiFi", "Funky Antenna", "LAN Woke Up Like This", "Sketchy Connection",
    "WiFi Speed Bump", "Router Party Like Its 1999", "The Ping Of Death Zone", "Connection Is Ghosting You", "Quirky Network",
    "Router Titanic Sinking", "Cocky LAN", "Gigabyte Or Bust", "Router Star Trek Beam Me", "WiFi Speaks Only Sass",
    "Router Needs A Hug", "Nosy Bandwidth", "Ratty Network", "Antenna Is Having A Moment", "House LANister",
    "Dorky Bandwidth", "Classy Modem", "Chatty Access Point", "WiFi Needs Space", "Ratty Hotspot",
    "Signal Is Ghosting You", "Bandwidth Bandit HQ", "Noisy Password", "Firewall Has Zero Chill Left", "Access Point Is On A Diet",
    "Jumpy Connection", "Firewall Needs A Snack Break", "Signal Is Done With Today", "Cocky Firewall", "Signal Is Feeling Petty",
    "Connection Needs Therapy Now", "Salty Access Point", "Dorky Ethernet", "Wireless Warfare Zone", "Password Needs Its Space",
    "Chatty Firewall", "Lazy Ethernet", "Byte Me Router", "Broadband Has Zero Chill Left", "Quirky Hotspot",
    "Connection Needs A Hug Please", "Bossy Bandwidth", "Funky Access Point", "WiFi Is In Its Feelings", "WiFi In Denial",

    // ---- Group 3: SSIDs 201-300 ----
    "Access Point Has Zero Chill Left", "Fancy LAN", "Loading More Excuses", "Corny Password", "Bossy Password",
    "Router Is Having A Moment", "Firewall Needs More Coffee", "Pretty Fly for a WiFi", "Connection Is Low Key Judging", "Ethernet Is In Its Feelings",
    "WiFi Norris Strikes Back", "Router Just Woke Up Grumpy", "Signal Refuses To Behave", "One Does Not Simply WiFi", "Password Has Zero Chill Left",
    "WiFi Says Absolutely Not", "Bandwidth Is Playing Favorites", "Sketchy Broadband", "Router Terminator Two", "Lazy Signal",
    "Router Has Trust Issues Now", "Shady Signal", "Noisy LAN", "Please Do Not Connect", "Feisty Broadband",
    "Clumsy Firewall", "Antenna Is Low Key Judging", "WiFi Or Die Trying", "WiFi Currently Napping", "Loading Existential Dread",
    "Ethernet Needs Therapy Now", "Wonky Modem", "Password Is On A Diet", "Router Jaws Bigger Boat", "Shady Hotspot",
    "Lazy Modem", "Tell My WiFi Love Her", "Fancy Network", "Firewall Has Trust Issues Now", "Sneaky Antenna",
    "Loading Emotional Support", "Spicy Ethernet", "Sketchy Firewall", "Zesty WiFi", "Jumpy Hotspot",
    "Sneaky WiFi", "Network Is On A Diet", "WiFi Needs A Vacation", "The Signal Is Weak Sauce", "Password Needs A Vacation",
    "Jumpy Network", "Fancy WiFi", "Corny Signal", "My WiFi Left Me On Read", "Salty Modem",
    "Hide Yo Kids Hide Yo WiFi", "Router With A Attitude", "Grumpy Firewall", "The Router Renaissance Era", "Wonky Network",
    "Router With Commitment Issues", "WiFi Cold Shoulder", "Antenna Is Plotting Something", "Fiber Optic Illusions", "Clumsy Access Point",
    "Router Rockstar Life", "You Shall Not Pass", "Broadband Is On A Diet", "Loading Awkward Eye Contact", "Router Rumor Mill",
    "Quirky LAN", "Modem Has Zero Chill Left", "Password Is A Secret Shh", "Dorky Broadband", "Spicy Firewall",
    "Grumpy WiFi", "Grumpy Modem", "Cocky Connection", "Feisty Modem", "Clumsy Antenna",
    "Antenna Is Way Too Extra", "WiFi Not Sorry", "Router Slightly Unhinged", "Zesty Ethernet", "Router Encanto No Signal",
    "Quirky WiFi", "Quirky Ethernet", "Password Is Plotting Something", "Snappy Broadband", "WiFi Says Hard Pass",
    "Cocky WiFi", "Router Aladdin Whole New", "Dorky Modem", "Router Requiem For A Dream", "Modem Is Out Of Office",
    "Password Speaks Only Sass", "Quirky Signal", "WiFi Needs More Coffee", "Antenna Is In Its Feelings", "Hotspot Is Currently Sulking",

    // ---- Group 4: SSIDs 301-400 ----
    "Free Hugs Not WiFi", "Ratty Connection", "Sneezy Hotspot", "Lazy Connection", "Signal Strength Questionable",
    "Please Stop Stealing WiFi", "Hotspot Just Woke Up Grumpy", "Router Has Left The Group", "Hotspot Speaks Only Sass", "Modem Madness Monday",
    "Loading Excuses", "Hotspot Is Done With Today", "Chatty Modem", "Router Runs On Spite", "Router Is Ghosting You",
    "WiFi Speaks Sarcasm Fluently", "Feisty WiFi", "Connection Woke Up Like This", "Loading Suspicious Silence", "Router Rendezvous Point",
    "Wonky Ethernet", "Spicy Password", "WiFi On A Break", "Loading Bad Decisions", "Feisty Router",
    "Salty Password", "Cocky Access Point", "Ethernet Is Living Its Truth", "WiFi Is Playing Favorites", "Noisy Connection",
    "Salty Ethernet", "WiFi On Do Not Disturb", "Get Your Own WiFi", "Classy Password", "Ethernet Is Plotting Something",
    "Nosy WiFi", "Router Slightly Concerning", "Router Toy Story Infinity", "Router Recon Mission", "Corny LAN",
    "Router Finding Nemo Signal", "Cranky Connection", "Grumpy Ethernet", "Nosy Modem", "Bandwidth Is Living Its Truth",
    "The Router Rhapsody Live", "Moody Firewall", "Loading Awkward Silence", "Sassy Router", "It Compiles Ship It",
    "WiFi Overdue For Therapy", "Password Needs More Coffee", "Antenna Needs More Coffee", "Wonky Connection", "Sneaky Password",
    "Sneezy Network", "Snappy Connection", "WiFi Or Nothing", "Broadband Refuses To Behave", "LAN Needs Therapy Now",
    "Sassy Access Point", "Password Needs A Snack Break", "Signal Needs A Vacation", "Connection Judges Your Life", "Chatty Signal",
    "Dorky Firewall", "Corny Hotspot", "Access Point Is Low Key Judging", "Router Bueller", "WiFi Currently Vibing",
    "Corny Router", "Sketchy Hotspot", "Zesty Access Point", "Loading Awkward Pause", "Feisty Bandwidth",
    "WiFi And Chill", "Firewall Is Having A Moment", "Cranky Broadband", "Shady Password", "Winter Is Coming WiFi",
    "Nosy Connection", "Feisty Firewall", "The LAN Down Under", "Salty Broadband", "LAN Needs A Vacation",
    "Noisy Access Point", "Password Is In Its Feelings", "Firmware Update Purgatory", "Nosy Signal", "Signal Is Playing Favorites",
    "Configuring Your Life", "Corny Network", "WiFi Is Living Its Truth", "Wonky Router", "Clumsy Router",
    "Ping Pong And Latency", "LAN Just Woke Up Grumpy", "Ratty LAN", "Ratty Modem", "Sneaky Access Point",

    // ---- Group 5: SSIDs 401-500 ----
    "LAN Is On A Diet", "Sketchy WiFi", "Sneezy Router", "Broadband Is Plotting Something", "Password Has Left The Group",
    "Funky Bandwidth", "The Ethernet Enigma", "WiFi Is Feeling Petty", "Funky Password", "Router Needs A Snack Break",
    "Network Is Plotting Something", "Dorky Router", "Moody WiFi", "Noisy Ethernet", "Firewall Speaks Only Sass",
    "Quirky Connection", "Sassy WiFi", "Grumpy Router", "Feisty LAN", "Signal Has Main Character Energy",
    "Network Needs A Snack Break", "Get Off My LAN", "The Modem Locum Tenens", "Classy Antenna", "Access Point Needs More Coffee",
    "Loading Trust Issues Now", "Router Bolt Superdog", "Connection Is Plotting Something", "Clumsy Network", "LAN Needs More Coffee",
    "Router I Hardly Know Her", "WiFi Judges Your Life", "Bill Wi the Science Fi", "Noisy Hotspot", "Signal Seeking Missile Here",
    "WiFi Has Trust Issues Now", "Bossy WiFi", "Classy Router", "Corny Antenna", "The Great Bandwidth Heist",
    "Router Rebellion Base", "Spicy Router", "Signal Needs A Hug Please", "Ethernet Needs Its Space", "Router Has Commitment Phobia",
    "Static IP Static Life", "Connection Is Way Too Extra", "The Cloud Has No Pants", "Bandwidth Is Feeling Petty", "Firewall Judges Your Life",
    "Broadband Is Not Your Friend", "Feisty Network", "Wireless Nightmare", "Funky Connection", "Bandwidth Needs Therapy Now",
    "Petty Modem", "Petty Router", "Loading Fake Enthusiasm", "Jumpy Firewall", "Moody Hotspot",
    "Spicy Antenna", "Antenna Needs Therapy Now", "Router Gonna Give You Up", "Router Full Of Regret", "Bossy Access Point",
    "Corny Bandwidth", "Cranky Modem", "I Believe I Can WiFi", "Password Runs On Spite", "Signal Is Living Its Truth",
    "Ratty Bandwidth", "404 WiFi Not Found", "Drop It Like Its Hotspot", "Password Is Currently Sulking", "Ratty WiFi",
    "Cocky Signal", "Router Riot Police", "LAN Needs Its Space", "Cranky Antenna", "Buffering My Feelings",
    "Wireless Repellent", "Cocky Antenna", "Grumpy Password", "WiFi Under Construction", "Sassy Antenna",
    "Router Roulette Wheel Spin", "Modem Operandi", "Router Avengers Assemble Now", "Bossy Firewall", "Sketchy LAN",
    "Bossy Modem", "WiFi Is Out Of Office", "The Great Router Bay", "Zesty Router", "Spicy LAN",
    "Chatty Connection", "Shady Access Point", "Noisy Network", "Lazy Antenna", "Hotspot Judges Your Life",

    // ---- Group 6: SSIDs 501-600 ----
    "Sassy Hotspot", "Petty Connection", "Moody Bandwidth", "Sassy LAN", "Chatty Router",
    "Sassy Connection", "Signal Boosted Ego Only", "Wonky WiFi", "Router Lion King Circle", "Classy Bandwidth",
    "Jumpy WiFi", "Loading Bad Wifi Puns", "Quirky Firewall", "Router Godfather Offer", "Signal Just Woke Up Grumpy",
    "Router Matrix Reloaded", "Noisy Router", "Loading Existential Crisis", "Router With Zero Chill", "Bandwidth Is Plotting Something",
    "Clumsy Broadband", "Zesty Network", "Password Is Classified Info", "Cranky WiFi", "WiFi Has Left The Chat",
    "Lazy Access Point", "Snappy Modem", "Loading Suspicious Activity", "Network Is Currently Sulking", "Sassy Ethernet",
    "Password Is Having A Moment", "Sassy Password", "Snappy Signal", "Loading Sarcasm Please Wait", "Modem Is Way Too Extra",
    "Moody Router", "Fancy Access Point", "Ethernet Is Out Of Office", "Access Point Blank Range", "Access Point Needs A Hug Please",
    "Zesty Hotspot", "Cranky Ethernet", "Nosy Hotspot", "Sneaky Ethernet", "Router Needs Snacks",
    "WiFi Is Ghosting You", "Wonky Firewall", "WiFi Playing Hard To Get", "Broadband Is Low Key Judging", "Broadband Speaks Only Sass",
    "Network Is Way Too Extra", "Sketchy Modem", "Router Full Of Puns", "Broadband Is Ghosting You", "Router Speaks Fluent Sass",
    "Cocky Router", "Lazy Firewall", "Fancy Connection", "Signal Is On A Diet", "Classy Hotspot",
    "Router Rehab Center", "Salty Hotspot", "Moody Access Point", "Signal Is In Its Feelings", "Moody Network",
    "Noisy Signal", "The Router Games", "Router Mood Swings", "Nosy Password", "Network Is Not Your Friend",
    "Moody Ethernet", "Antenna Is Ghosting You", "Cocky Broadband", "Router Mulan Reflection", "Lazy Router",
    "Connection Speaks Only Sass", "Fancy Bandwidth", "Broadband Is Out Of Office", "Sneezy Connection", "Never Gonna Give You Router",
    "Router Up And Away", "Funky Network", "The Promised LAN", "Loading Awkward Small Talk", "Password Protected Feelings",
    "Ratty Router", "Clumsy LAN", "Router Radio Silence Now", "Sketchy Bandwidth", "Access Point Is Out Of Office",
    "Funky Modem", "Broadband Needs Therapy Now", "Connection Has Left The Group", "Spicy Broadband", "Loading Midlife Crisis",
    "Modem Needs Its Space", "Hotspot Needs A Snack Break", "Darth Router", "Access Point Judges Your Life", "Connection Is Done With Today",

    // ---- Group 7: SSIDs 601-700 ----
    "WiFi Speaks In Riddles", "Bossy Antenna", "No Free WiFi For You", "Snappy Firewall", "Ethernet Is Low Key Judging",
    "The Cake Is A LAN", "Router Reruns All Day", "Bossy Broadband", "Zesty Broadband", "WiFi Is My Copilot",
    "Access Point Is Done With Today", "Feisty Connection", "Router Norris", "Password Rejected Rudely", "Router Jurassic Park",
    "Broadband Is Currently Sulking", "Zesty Antenna", "LAN Needs A Hug Please", "Silent But Deadly WiFi", "Router Needs Therapy",
    "WiFi Ghost Town", "Fancy Ethernet", "Please Password Responsibly", "Router With Zero Patience", "Router Shrek Is Love",
    "Signal Weaker Than Coffee", "Sneaky Bandwidth", "Antenna Runs On Spite", "Router Needs A Nap", "Loading Petty Comments",
    "Modem Runs On Spite", "Router Refuses Eye Contact", "Sneezy Access Point", "Antenna Is Out Of Office", "Signal Strength Emotional",
    "Jumpy Password", "Chatty Ethernet", "Noisy Firewall", "Router Needs Therapy Now", "Router Is Living Its Truth",
    "Cranky Bandwidth", "Lazy Password", "Shady Firewall", "Petty Broadband", "Nosy LAN",
    "Password Guarded By Dragons", "Ethernet Needs A Hug Please", "Cocky Ethernet", "Corny Connection", "Antenna Just Woke Up Grumpy",
    "Signal Bouncing Off Walls", "Signal Is Low Key Judging", "Petty Password", "Zesty Signal", "Sketchy Router",
    "Password Is Playing Favorites", "Router And Chill Tonight", "Router Ratatouille Chef", "Wonky Broadband", "Password Locked In Vault",
    "Router Coco Remember Me", "Signal Lost In Translation", "Access Point Has Left The Group", "Shady Bandwidth", "Access Point Is Not Your Friend",
    "Funky Router", "Connection Is Out Of Office", "Feisty Hotspot", "Clumsy Bandwidth", "Bandwidth Is In Its Feelings",
    "Wu Tang LAN", "Network Woke Up Like This", "Zesty Bandwidth", "Cranky Firewall", "Shady Modem",
    "Loading Passive Aggression", "Spicy Modem", "Router Riddle Me This", "WiFi Refuses To Behave", "Sneaky Signal",
    "Salty Signal", "Sneaky Router", "WiFi On Thin Ice", "Shady Network", "WiFi Runs On Vibes",
    "Router Rangers Assemble", "Ratty Firewall", "Router Fresh Prince Of LAN", "Spicy Access Point", "WiFi Ghosted Me",
    "Connection Refuses To Behave", "Firewall Is Done With Today", "Modem Is Having A Moment", "Signal Needs Therapy Now", "Ctrl Alt Defeat",
    "Snappy LAN", "Access Point Needs A Vacation", "Sneezy Antenna", "Signal Woke Up Like This", "Signal Is Way Too Extra",

    // ---- Group 8: SSIDs 701-800 ----
    "Router Overlord", "WiFi Is Way Too Extra", "Firewall Just Woke Up Grumpy", "WiFi Very Dramatic", "Petty Firewall",
    "Hotspot Is Feeling Petty", "Loading Unnecessary Drama", "Router To The Danger Zone", "Signal Speaks Only Sass", "WiFi Has Main Character Energy",
    "Router Radio Free Nowhere", "Abraham Linksys", "Cocky Hotspot", "Password Refuses To Behave", "Shady Antenna",
    "Grumpy Access Point", "Quirky Modem", "Classy Access Point", "Dorky Signal", "Classy WiFi",
    "Modem Mayhem Downtown", "Lazy LAN", "Grumpy Antenna", "Petty Antenna", "Petty Access Point",
    "Ratty Password", "Lazy Bandwidth", "WiFi On Strike Today", "Wonky Hotspot", "Sassy Broadband",
    "Password Encrypted With Sarcasm", "Click Here For Virus", "Packet Loss Prevention Squad", "Ethernet Has Left The Group", "Wonky Signal",
    "Corny Access Point", "Router Ranger", "Bossy Ethernet", "Feisty Password", "Signal Is Out Of Office",
    "Ratty Access Point", "Router Overthinking Everything", "Sneezy Modem", "Noisy Bandwidth", "Corny Firewall",
    "Zesty Firewall", "Bandwidth Blues Band", "Broadband Judges Your Life", "Loading Please Wait", "Ye Olde WiFi",
    "Router Incredibles Family", "Nosy Router", "Salty Network", "Bossy Hotspot", "Broadband Is Feeling Petty",
    "Chatty Password", "Classy Ethernet", "Router To Nowhere", "Router Speaks Only Sass", "Spicy WiFi",
    "Router Has Main Character Energy", "Moody Signal", "Router To The Future", "Router Inception Level Two", "Signal Playing Coy",
    "Ratty Antenna", "Classy Network", "Clumsy Modem", "Sneezy Bandwidth", "Access Point Is In Its Feelings",
    "Password Has Trust Issues Now", "The Router Resistance Front", "Grumpy Connection", "Fancy Hotspot", "It Hurts When IP",
    "WiFi Says No Thanks", "Dorky Hotspot", "Network Is Having A Moment", "Shady LAN", "Router Named Bob",
    "Bandwidth Is Done With Today", "Snappy Bandwidth", "Shady WiFi", "Clumsy Hotspot", "Router Grease Lightning",
    "WiFi On Airplane Mode", "Router On A Diet", "Sneezy LAN", "Sketchy Antenna", "Router Is Currently Sulking",
    "Feisty Antenna", "Broadband Has Trust Issues Now", "Spicy Bandwidth", "Antenna Has Trust Issues Now", "Loading Awkward Compliments",
    "Modem Has Trust Issues Now", "Nosy Antenna", "Sassy Firewall", "Connection Is Living Its Truth", "Password Is Not Your Friend",

    // ---- Group 9: SSIDs 801-900 ----
    "Modem Has Left The Group", "Router Moana Ocean Calls", "Ethernet Is Ghosting You", "Chatty Broadband", "Antenna Is On A Diet",
    "WiFi Is Low Key Judging", "Wonky Access Point", "Spicy Hotspot", "Network Is Done With Today", "FBI Surveillance Van",
    "Firewall Needs Therapy Now", "Petty Network", "LAN Runs On Spite", "Petty Hotspot", "Modem Judges Your Life",
    "Router Is Out Of Office", "Moody Password", "Lazy Broadband", "Modem Is Ghosting You", "This WiFi Bites",
    "Spicy Network", "Sassy Modem", "Sketchy Network", "Zesty Connection", "Noisy Modem",
    "Antenna Refuses To Behave", "Petty Bandwidth", "Wonky LAN", "Signal Strength Zero Hero", "Nosy Network",
    "Salty Connection", "Connection Is In Its Feelings", "Sneezy Signal", "This Router Judges You", "Ethernet Is Playing Favorites",
    "Router Die Hard", "Ratty Broadband", "Router Is Playing Favorites", "Router Is Done With Today", "Router Cars Lightning Fast",
    "Salty Firewall", "Funky Ethernet", "Router Home Alone", "Cocky Bandwidth", "Fancy Broadband",
    "Chill Your Own WiFi", "LAN Is Plotting Something", "Router With No Chill", "Moody Antenna", "Ratty Signal",
    "Router Wall E Alone", "Noisy Broadband", "Cranky Network", "Access Point Is Feeling Petty", "Salty Antenna",
    "Modem Is Living Its Truth", "Fancy Signal", "Chatty Antenna", "Router With A Grudge", "Router Malfunction Beep",
    "Wonky Bandwidth", "Ethernet Needs More Coffee", "Router Playing Favorites", "Bossy Connection", "Shady Ethernet",
    "Jumpy Router", "Modem Has Main Character Energy", "Clumsy WiFi", "Connection Has Trust Issues Now", "WiFi Not In The Mood",
    "Connection Has Zero Chill Left", "Sassy Signal", "Firewall Has Left The Group", "Petty WiFi", "Access Point Is Living Its Truth",
    "Corny Ethernet", "Grumpy Bandwidth", "Bossy Router", "Quirky Antenna", "Nosy Ethernet",
    "Salty Bandwidth", "LAN Is Currently Sulking", "Password Is Password", "WiFi Not Feeling It", "Quirky Bandwidth",
    "Feisty Signal", "Router Being Extra Petty", "LAN Has Left The Group", "Classy Connection", "Snappy Router",
    "Not The WiFi Youre Looking For", "Router With Anxiety", "Fancy Modem", "Bossy LAN", "Router Needs Validation",
    "Sketchy Password", "Dorky Connection", "Jumpy Access Point", "Ethernet Is Done With Today", "Classy LAN",

    // ---- Group 10: SSIDs 901-1000 ----
    "Ethernet Has Zero Chill Left", "Firewall Needs A Hug Please", "Life In The Fast LAN", "Funky Broadband", "Dorky Antenna",
    "Router Back To The LAN", "Router Skywalker", "Clumsy Password", "WiFi Is Not Your Friend", "Cranky Hotspot",
    "WiFi Judging Silently", "Snappy Network", "Grumpy LAN", "I Am Not A Router", "Loading Life Choices",
    "Kilobyte Crisis Center", "WiFi Currently Petty", "Router With Big Feelings", "Ethernet Just Woke Up Grumpy", "Jumpy LAN",
    "Snappy Password", "Nosy Firewall", "Ethernet Is Not Your Friend", "WiFi Not Impressed", "Router Hood Prince Of Thieves",
    "Classy Firewall", "Cranky LAN", "Chatty Hotspot", "Signal Bouncing Around Confused", "Corny Modem",
    "Password Guarded Fiercely", "Moody Broadband", "Shady Router", "Dorky WiFi", "Router Full Of Attitude",
    "WiFi Broke Up With Me", "Router Is Not Your Friend", "Connection Needs Its Space", "Jumpy Bandwidth", "Grumpy Network",
    "Sneezy Broadband", "The Wireless Whisperer", "Static Cling Network", "Connection Is On A Diet", "Router Being Dramatic Today",
    "Sneaky Hotspot", "WiFi Needs Its Space", "Bandwidth Is Way Too Extra", "WiFi Is Currently Sulking", "Sneaky Network",
    "Funky WiFi", "Zesty Password", "Snappy Access Point", "Clumsy Connection", "Access Point Runs On Spite",
    "Funky Hotspot", "Grumpy Signal", "Grumpy Hotspot", "Shady Connection", "Shady Broadband",
    "Quirky Password", "Antenna Speaks Only Sass", "Sassy Network", "Jumpy Antenna", "Chatty Network",
    "Grumpy Broadband", "Sneaky LAN", "Feisty Ethernet", "Firewall Is Living Its Truth", "Chatty LAN",
    "Bandwidth Is Ghosting You", "Bandwidth Just Woke Up Grumpy", "The Great Firewall Of Us", "Network Needs A Hug Please", "Router Is On A Diet",
    "Loading 99 Percent", "Router Has Trust Issues", "Router Vader I Am Your Signal", "Snappy Hotspot", "WiFi Stole My Bike",
    "Cranky Password", "Broadband Runs On Spite", "Moody Modem", "Chatty WiFi", "Noisy WiFi",
    "Funky Signal", "WiFi Not Today Satan", "Signal Is Having A Moment", "Petty Ethernet", "Snappy WiFi",
    "Fancy Password", "Petty Signal", "Access Denied Forever", "Corny WiFi", "Modem Needs A Snack Break",
    "Zesty Modem", "Router Ghostbusters Call", "Broadband Needs Its Space", "Router Currently Judging", "Snappy Ethernet"
};

const int fakeSSIDsCount = sizeof(fakeSSIDs) / sizeof(fakeSSIDs[0]);