#include <Arduino.h>
#include <WiFi.h>
#include <esp_wifi.h>

// List containing all 1000 fake Wi-Fi SSIDs.
const char* fakeSSIDs[] = {
    "Mom Said No WiFi 1",
    "Definitely Not WiFi 1",
    "Loading... Please Wait 1",
    "Password Is Password 1",
    "LAN Solo 1",
    "It Hurts When IP 1",
    "Pretty Fly for a WiFi 1",
    "Nacho WiFi 1",
    "Tell My Router I Love Her 1",
    "404 WiFi Not Found 1",
    "The LAN Before Time 1",
    "Silence of the LANs 1",
    "Lord of the Pings 1",
    "Game of Phones 1",
    "Ping Me Maybe 1",
    "Wi Believe I Can Fi 1",
    "Keep Calm and Reboot 1",
    "Router? I Hardly Know Her 1",
    "No Free WiFi Here 1",
    "Buffering Forever 1",
    "Definitely A Microwave 1",
    "Ask Dad For Password 1",
    "Connecting Emotionally 1",
    "WiFi and Chill 1",
    "Unstable But Available 1",
    "This Is My Hotspot 1",
    "Yeet The Router 1",
    "Reboot and Pray 1",
    "Signal Lost Again 1",
    "Internet Went Outside 1",
    "Trust Me Im An Engineer 1",
    "Definitely Not Your Router 1",
    "LAN Me Alone 1",
    "Pretty Fly For A WiFi 1",
    "The Password Is Wrong 1",
    "Loading Personality 1",
    "404 Brain Not Found 1",
    "Low Battery High Hopes 1",
    "WiFi Has Left The Chat 1",
    "Router In Disguise 1",
    "Ping Pong Palace 1",
    "House of LAN 1",
    "May The WiFi Be With You 1",
    "One Does Not Simply Connect 1",
    "Winter Is Buffering 1",
    "You Shall Not Passcode 1",
    "The Ping Awakens 1",
    "Return of the WiFi 1",
    "Attack of the Clones 1",
    "Revenge of the Router 1",
    "A New LAN 1",
    "Mom Said No WiFi 2",
    "Definitely Not WiFi 2",
    "Loading... Please Wait 2",
    "Password Is Password 2",
    "LAN Solo 2",
    "It Hurts When IP 2",
    "Pretty Fly for a WiFi 2",
    "Nacho WiFi 2",
    "Tell My Router I Love Her 2",
    "404 WiFi Not Found 2",
    "The LAN Before Time 2",
    "Silence of the LANs 2",
    "Lord of the Pings 2",
    "Game of Phones 2",
    "Ping Me Maybe 2",
    "Wi Believe I Can Fi 2",
    "Keep Calm and Reboot 2",
    "Router? I Hardly Know Her 2",
    "No Free WiFi Here 2",
    "Buffering Forever 2",
    "Definitely A Microwave 2",
    "Ask Dad For Password 2",
    "Connecting Emotionally 2",
    "WiFi and Chill 2",
    "Unstable But Available 2",
    "This Is My Hotspot 2",
    "Yeet The Router 2",
    "Reboot and Pray 2",
    "Signal Lost Again 2",
    "Internet Went Outside 2",
    "Trust Me Im An Engineer 2",
    "Definitely Not Your Router 2",
    "LAN Me Alone 2",
    "Pretty Fly For A WiFi 2",
    "The Password Is Wrong 2",
    "Loading Personality 2",
    "404 Brain Not Found 2",
    "Low Battery High Hopes 2",
    "WiFi Has Left The Chat 2",
    "Router In Disguise 2",
    "Ping Pong Palace 2",
    "House of LAN 2",
    "May The WiFi Be With You 2",
    "One Does Not Simply Connect 2",
    "Winter Is Buffering 2",
    "You Shall Not Passcode 2",
    "The Ping Awakens 2",
    "Return of the WiFi 2",
    "Attack of the Clones 2",
    "Revenge of the Router 2",
    "A New LAN 2",
    "Mom Said No WiFi 3",
    "Definitely Not WiFi 3",
    "Loading... Please Wait 3",
    "Password Is Password 3",
    "LAN Solo 3",
    "It Hurts When IP 3",
    "Pretty Fly for a WiFi 3",
    "Nacho WiFi 3",
    "Tell My Router I Love Her 3",
    "404 WiFi Not Found 3",
    "The LAN Before Time 3",
    "Silence of the LANs 3",
    "Lord of the Pings 3",
    "Game of Phones 3",
    "Ping Me Maybe 3",
    "Wi Believe I Can Fi 3",
    "Keep Calm and Reboot 3",
    "Router? I Hardly Know Her 3",
    "No Free WiFi Here 3",
    "Buffering Forever 3",
    "Definitely A Microwave 3",
    "Ask Dad For Password 3",
    "Connecting Emotionally 3",
    "WiFi and Chill 3",
    "Unstable But Available 3",
    "This Is My Hotspot 3",
    "Yeet The Router 3",
    "Reboot and Pray 3",
    "Signal Lost Again 3",
    "Internet Went Outside 3",
    "Trust Me Im An Engineer 3",
    "Definitely Not Your Router 3",
    "LAN Me Alone 3",
    "Pretty Fly For A WiFi 3",
    "The Password Is Wrong 3",
    "Loading Personality 3",
    "404 Brain Not Found 3",
    "Low Battery High Hopes 3",
    "WiFi Has Left The Chat 3",
    "Router In Disguise 3",
    "Ping Pong Palace 3",
    "House of LAN 3",
    "May The WiFi Be With You 3",
    "One Does Not Simply Connect 3",
    "Winter Is Buffering 3",
    "You Shall Not Passcode 3",
    "The Ping Awakens 3",
    "Return of the WiFi 3",
    "Attack of the Clones 3",
    "Revenge of the Router 3",
    "A New LAN 3",
    "Mom Said No WiFi 4",
    "Definitely Not WiFi 4",
    "Loading... Please Wait 4",
    "Password Is Password 4",
    "LAN Solo 4",
    "It Hurts When IP 4",
    "Pretty Fly for a WiFi 4",
    "Nacho WiFi 4",
    "Tell My Router I Love Her 4",
    "404 WiFi Not Found 4",
    "The LAN Before Time 4",
    "Silence of the LANs 4",
    "Lord of the Pings 4",
    "Game of Phones 4",
    "Ping Me Maybe 4",
    "Wi Believe I Can Fi 4",
    "Keep Calm and Reboot 4",
    "Router? I Hardly Know Her 4",
    "No Free WiFi Here 4",
    "Buffering Forever 4",
    "Definitely A Microwave 4",
    "Ask Dad For Password 4",
    "Connecting Emotionally 4",
    "WiFi and Chill 4",
    "Unstable But Available 4",
    "This Is My Hotspot 4",
    "Yeet The Router 4",
    "Reboot and Pray 4",
    "Signal Lost Again 4",
    "Internet Went Outside 4",
    "Trust Me Im An Engineer 4",
    "Definitely Not Your Router 4",
    "LAN Me Alone 4",
    "Pretty Fly For A WiFi 4",
    "The Password Is Wrong 4",
    "Loading Personality 4",
    "404 Brain Not Found 4",
    "Low Battery High Hopes 4",
    "WiFi Has Left The Chat 4",
    "Router In Disguise 4",
    "Ping Pong Palace 4",
    "House of LAN 4",
    "May The WiFi Be With You 4",
    "One Does Not Simply Connect 4",
    "Winter Is Buffering 4",
    "You Shall Not Passcode 4",
    "The Ping Awakens 4",
    "Return of the WiFi 4",
    "Attack of the Clones 4",
    "Revenge of the Router 4",
    "A New LAN 4",
    "Mom Said No WiFi 5",
    "Definitely Not WiFi 5",
    "Loading... Please Wait 5",
    "Password Is Password 5",
    "LAN Solo 5",
    "It Hurts When IP 5",
    "Pretty Fly for a WiFi 5",
    "Nacho WiFi 5",
    "Tell My Router I Love Her 5",
    "404 WiFi Not Found 5",
    "The LAN Before Time 5",
    "Silence of the LANs 5",
    "Lord of the Pings 5",
    "Game of Phones 5",
    "Ping Me Maybe 5",
    "Wi Believe I Can Fi 5",
    "Keep Calm and Reboot 5",
    "Router? I Hardly Know Her 5",
    "No Free WiFi Here 5",
    "Buffering Forever 5",
    "Definitely A Microwave 5",
    "Ask Dad For Password 5",
    "Connecting Emotionally 5",
    "WiFi and Chill 5",
    "Unstable But Available 5",
    "This Is My Hotspot 5",
    "Yeet The Router 5",
    "Reboot and Pray 5",
    "Signal Lost Again 5",
    "Internet Went Outside 5",
    "Trust Me Im An Engineer 5",
    "Definitely Not Your Router 5",
    "LAN Me Alone 5",
    "Pretty Fly For A WiFi 5",
    "The Password Is Wrong 5",
    "Loading Personality 5",
    "404 Brain Not Found 5",
    "Low Battery High Hopes 5",
    "WiFi Has Left The Chat 5",
    "Router In Disguise 5",
    "Ping Pong Palace 5",
    "House of LAN 5",
    "May The WiFi Be With You 5",
    "One Does Not Simply Connect 5",
    "Winter Is Buffering 5",
    "You Shall Not Passcode 5",
    "The Ping Awakens 5",
    "Return of the WiFi 5",
    "Attack of the Clones 5",
    "Revenge of the Router 5",
    "A New LAN 5",
    "Mom Said No WiFi 6",
    "Definitely Not WiFi 6",
    "Loading... Please Wait 6",
    "Password Is Password 6",
    "LAN Solo 6",
    "It Hurts When IP 6",
    "Pretty Fly for a WiFi 6",
    "Nacho WiFi 6",
    "Tell My Router I Love Her 6",
    "404 WiFi Not Found 6",
    "The LAN Before Time 6",
    "Silence of the LANs 6",
    "Lord of the Pings 6",
    "Game of Phones 6",
    "Ping Me Maybe 6",
    "Wi Believe I Can Fi 6",
    "Keep Calm and Reboot 6",
    "Router? I Hardly Know Her 6",
    "No Free WiFi Here 6",
    "Buffering Forever 6",
    "Definitely A Microwave 6",
    "Ask Dad For Password 6",
    "Connecting Emotionally 6",
    "WiFi and Chill 6",
    "Unstable But Available 6",
    "This Is My Hotspot 6",
    "Yeet The Router 6",
    "Reboot and Pray 6",
    "Signal Lost Again 6",
    "Internet Went Outside 6",
    "Trust Me Im An Engineer 6",
    "Definitely Not Your Router 6",
    "LAN Me Alone 6",
    "Pretty Fly For A WiFi 6",
    "The Password Is Wrong 6",
    "Loading Personality 6",
    "404 Brain Not Found 6",
    "Low Battery High Hopes 6",
    "WiFi Has Left The Chat 6",
    "Router In Disguise 6",
    "Ping Pong Palace 6",
    "House of LAN 6",
    "May The WiFi Be With You 6",
    "One Does Not Simply Connect 6",
    "Winter Is Buffering 6",
    "You Shall Not Passcode 6",
    "The Ping Awakens 6",
    "Return of the WiFi 6",
    "Attack of the Clones 6",
    "Revenge of the Router 6",
    "A New LAN 6",
    "Mom Said No WiFi 7",
    "Definitely Not WiFi 7",
    "Loading... Please Wait 7",
    "Password Is Password 7",
    "LAN Solo 7",
    "It Hurts When IP 7",
    "Pretty Fly for a WiFi 7",
    "Nacho WiFi 7",
    "Tell My Router I Love Her 7",
    "404 WiFi Not Found 7",
    "The LAN Before Time 7",
    "Silence of the LANs 7",
    "Lord of the Pings 7",
    "Game of Phones 7",
    "Ping Me Maybe 7",
    "Wi Believe I Can Fi 7",
    "Keep Calm and Reboot 7",
    "Router? I Hardly Know Her 7",
    "No Free WiFi Here 7",
    "Buffering Forever 7",
    "Definitely A Microwave 7",
    "Ask Dad For Password 7",
    "Connecting Emotionally 7",
    "WiFi and Chill 7",
    "Unstable But Available 7",
    "This Is My Hotspot 7",
    "Yeet The Router 7",
    "Reboot and Pray 7",
    "Signal Lost Again 7",
    "Internet Went Outside 7",
    "Trust Me Im An Engineer 7",
    "Definitely Not Your Router 7",
    "LAN Me Alone 7",
    "Pretty Fly For A WiFi 7",
    "The Password Is Wrong 7",
    "Loading Personality 7",
    "404 Brain Not Found 7",
    "Low Battery High Hopes 7",
    "WiFi Has Left The Chat 7",
    "Router In Disguise 7",
    "Ping Pong Palace 7",
    "House of LAN 7",
    "May The WiFi Be With You 7",
    "One Does Not Simply Connect 7",
    "Winter Is Buffering 7",
    "You Shall Not Passcode 7",
    "The Ping Awakens 7",
    "Return of the WiFi 7",
    "Attack of the Clones 7",
    "Revenge of the Router 7",
    "A New LAN 7",
    "Mom Said No WiFi 8",
    "Definitely Not WiFi 8",
    "Loading... Please Wait 8",
    "Password Is Password 8",
    "LAN Solo 8",
    "It Hurts When IP 8",
    "Pretty Fly for a WiFi 8",
    "Nacho WiFi 8",
    "Tell My Router I Love Her 8",
    "404 WiFi Not Found 8",
    "The LAN Before Time 8",
    "Silence of the LANs 8",
    "Lord of the Pings 8",
    "Game of Phones 8",
    "Ping Me Maybe 8",
    "Wi Believe I Can Fi 8",
    "Keep Calm and Reboot 8",
    "Router? I Hardly Know Her 8",
    "No Free WiFi Here 8",
    "Buffering Forever 8",
    "Definitely A Microwave 8",
    "Ask Dad For Password 8",
    "Connecting Emotionally 8",
    "WiFi and Chill 8",
    "Unstable But Available 8",
    "This Is My Hotspot 8",
    "Yeet The Router 8",
    "Reboot and Pray 8",
    "Signal Lost Again 8",
    "Internet Went Outside 8",
    "Trust Me Im An Engineer 8",
    "Definitely Not Your Router 8",
    "LAN Me Alone 8",
    "Pretty Fly For A WiFi 8",
    "The Password Is Wrong 8",
    "Loading Personality 8",
    "404 Brain Not Found 8",
    "Low Battery High Hopes 8",
    "WiFi Has Left The Chat 8",
    "Router In Disguise 8",
    "Ping Pong Palace 8",
    "House of LAN 8",
    "May The WiFi Be With You 8",
    "One Does Not Simply Connect 8",
    "Winter Is Buffering 8",
    "You Shall Not Passcode 8",
    "The Ping Awakens 8",
    "Return of the WiFi 8",
    "Attack of the Clones 8",
    "Revenge of the Router 8",
    "A New LAN 8",
    "Mom Said No WiFi 9",
    "Definitely Not WiFi 9",
    "Loading... Please Wait 9",
    "Password Is Password 9",
    "LAN Solo 9",
    "It Hurts When IP 9",
    "Pretty Fly for a WiFi 9",
    "Nacho WiFi 9",
    "Tell My Router I Love Her 9",
    "404 WiFi Not Found 9",
    "The LAN Before Time 9",
    "Silence of the LANs 9",
    "Lord of the Pings 9",
    "Game of Phones 9",
    "Ping Me Maybe 9",
    "Wi Believe I Can Fi 9",
    "Keep Calm and Reboot 9",
    "Router? I Hardly Know Her 9",
    "No Free WiFi Here 9",
    "Buffering Forever 9",
    "Definitely A Microwave 9",
    "Ask Dad For Password 9",
    "Connecting Emotionally 9",
    "WiFi and Chill 9",
    "Unstable But Available 9",
    "This Is My Hotspot 9",
    "Yeet The Router 9",
    "Reboot and Pray 9",
    "Signal Lost Again 9",
    "Internet Went Outside 9",
    "Trust Me Im An Engineer 9",
    "Definitely Not Your Router 9",
    "LAN Me Alone 9",
    "Pretty Fly For A WiFi 9",
    "The Password Is Wrong 9",
    "Loading Personality 9",
    "404 Brain Not Found 9",
    "Low Battery High Hopes 9",
    "WiFi Has Left The Chat 9",
    "Router In Disguise 9",
    "Ping Pong Palace 9",
    "House of LAN 9",
    "May The WiFi Be With You 9",
    "One Does Not Simply Connect 9",
    "Winter Is Buffering 9",
    "You Shall Not Passcode 9",
    "The Ping Awakens 9",
    "Return of the WiFi 9",
    "Attack of the Clones 9",
    "Revenge of the Router 9",
    "A New LAN 9",
    "Mom Said No WiFi 10",
    "Definitely Not WiFi 10",
    "Loading... Please Wait 10",
    "Password Is Password 10",
    "LAN Solo 10",
    "It Hurts When IP 10",
    "Pretty Fly for a WiFi 10",
    "Nacho WiFi 10",
    "Tell My Router I Love Her 10",
    "404 WiFi Not Found 10",
    "The LAN Before Time 10",
    "Silence of the LANs 10",
    "Lord of the Pings 10",
    "Game of Phones 10",
    "Ping Me Maybe 10",
    "Wi Believe I Can Fi 10",
    "Keep Calm and Reboot 10",
    "Router? I Hardly Know Her 10",
    "No Free WiFi Here 10",
    "Buffering Forever 10",
    "Definitely A Microwave 10",
    "Ask Dad For Password 10",
    "Connecting Emotionally 10",
    "WiFi and Chill 10",
    "Unstable But Available 10",
    "This Is My Hotspot 10",
    "Yeet The Router 10",
    "Reboot and Pray 10",
    "Signal Lost Again 10",
    "Internet Went Outside 10",
    "Trust Me Im An Engineer 10",
    "Definitely Not Your Router 10",
    "LAN Me Alone 10",
    "Pretty Fly For A WiFi 10",
    "The Password Is Wrong 10",
    "Loading Personality 10",
    "404 Brain Not Found 10",
    "Low Battery High Hopes 10",
    "WiFi Has Left The Chat 10",
    "Router In Disguise 10",
    "Ping Pong Palace 10",
    "House of LAN 10",
    "May The WiFi Be With You 10",
    "One Does Not Simply Connect 10",
    "Winter Is Buffering 10",
    "You Shall Not Passcode 10",
    "The Ping Awakens 10",
    "Return of the WiFi 10",
    "Attack of the Clones 10",
    "Revenge of the Router 10",
    "A New LAN 10",
    "Mom Said No WiFi 11",
    "Definitely Not WiFi 11",
    "Loading... Please Wait 11",
    "Password Is Password 11",
    "LAN Solo 11",
    "It Hurts When IP 11",
    "Pretty Fly for a WiFi 11",
    "Nacho WiFi 11",
    "Tell My Router I Love Her 11",
    "404 WiFi Not Found 11",
    "The LAN Before Time 11",
    "Silence of the LANs 11",
    "Lord of the Pings 11",
    "Game of Phones 11",
    "Ping Me Maybe 11",
    "Wi Believe I Can Fi 11",
    "Keep Calm and Reboot 11",
    "Router? I Hardly Know Her 11",
    "No Free WiFi Here 11",
    "Buffering Forever 11",
    "Definitely A Microwave 11",
    "Ask Dad For Password 11",
    "Connecting Emotionally 11",
    "WiFi and Chill 11",
    "Unstable But Available 11",
    "This Is My Hotspot 11",
    "Yeet The Router 11",
    "Reboot and Pray 11",
    "Signal Lost Again 11",
    "Internet Went Outside 11",
    "Trust Me Im An Engineer 11",
    "Definitely Not Your Router 11",
    "LAN Me Alone 11",
    "Pretty Fly For A WiFi 11",
    "The Password Is Wrong 11",
    "Loading Personality 11",
    "404 Brain Not Found 11",
    "Low Battery High Hopes 11",
    "WiFi Has Left The Chat 11",
    "Router In Disguise 11",
    "Ping Pong Palace 11",
    "House of LAN 11",
    "May The WiFi Be With You 11",
    "One Does Not Simply Connect 11",
    "Winter Is Buffering 11",
    "You Shall Not Passcode 11",
    "The Ping Awakens 11",
    "Return of the WiFi 11",
    "Attack of the Clones 11",
    "Revenge of the Router 11",
    "A New LAN 11",
    "Mom Said No WiFi 12",
    "Definitely Not WiFi 12",
    "Loading... Please Wait 12",
    "Password Is Password 12",
    "LAN Solo 12",
    "It Hurts When IP 12",
    "Pretty Fly for a WiFi 12",
    "Nacho WiFi 12",
    "Tell My Router I Love Her 12",
    "404 WiFi Not Found 12",
    "The LAN Before Time 12",
    "Silence of the LANs 12",
    "Lord of the Pings 12",
    "Game of Phones 12",
    "Ping Me Maybe 12",
    "Wi Believe I Can Fi 12",
    "Keep Calm and Reboot 12",
    "Router? I Hardly Know Her 12",
    "No Free WiFi Here 12",
    "Buffering Forever 12",
    "Definitely A Microwave 12",
    "Ask Dad For Password 12",
    "Connecting Emotionally 12",
    "WiFi and Chill 12",
    "Unstable But Available 12",
    "This Is My Hotspot 12",
    "Yeet The Router 12",
    "Reboot and Pray 12",
    "Signal Lost Again 12",
    "Internet Went Outside 12",
    "Trust Me Im An Engineer 12",
    "Definitely Not Your Router 12",
    "LAN Me Alone 12",
    "Pretty Fly For A WiFi 12",
    "The Password Is Wrong 12",
    "Loading Personality 12",
    "404 Brain Not Found 12",
    "Low Battery High Hopes 12",
    "WiFi Has Left The Chat 12",
    "Router In Disguise 12",
    "Ping Pong Palace 12",
    "House of LAN 12",
    "May The WiFi Be With You 12",
    "One Does Not Simply Connect 12",
    "Winter Is Buffering 12",
    "You Shall Not Passcode 12",
    "The Ping Awakens 12",
    "Return of the WiFi 12",
    "Attack of the Clones 12",
    "Revenge of the Router 12",
    "A New LAN 12",
    "Mom Said No WiFi 13",
    "Definitely Not WiFi 13",
    "Loading... Please Wait 13",
    "Password Is Password 13",
    "LAN Solo 13",
    "It Hurts When IP 13",
    "Pretty Fly for a WiFi 13",
    "Nacho WiFi 13",
    "Tell My Router I Love Her 13",
    "404 WiFi Not Found 13",
    "The LAN Before Time 13",
    "Silence of the LANs 13",
    "Lord of the Pings 13",
    "Game of Phones 13",
    "Ping Me Maybe 13",
    "Wi Believe I Can Fi 13",
    "Keep Calm and Reboot 13",
    "Router? I Hardly Know Her 13",
    "No Free WiFi Here 13",
    "Buffering Forever 13",
    "Definitely A Microwave 13",
    "Ask Dad For Password 13",
    "Connecting Emotionally 13",
    "WiFi and Chill 13",
    "Unstable But Available 13",
    "This Is My Hotspot 13",
    "Yeet The Router 13",
    "Reboot and Pray 13",
    "Signal Lost Again 13",
    "Internet Went Outside 13",
    "Trust Me Im An Engineer 13",
    "Definitely Not Your Router 13",
    "LAN Me Alone 13",
    "Pretty Fly For A WiFi 13",
    "The Password Is Wrong 13",
    "Loading Personality 13",
    "404 Brain Not Found 13",
    "Low Battery High Hopes 13",
    "WiFi Has Left The Chat 13",
    "Router In Disguise 13",
    "Ping Pong Palace 13",
    "House of LAN 13",
    "May The WiFi Be With You 13",
    "One Does Not Simply Connect 13",
    "Winter Is Buffering 13",
    "You Shall Not Passcode 13",
    "The Ping Awakens 13",
    "Return of the WiFi 13",
    "Attack of the Clones 13",
    "Revenge of the Router 13",
    "A New LAN 13",
    "Mom Said No WiFi 14",
    "Definitely Not WiFi 14",
    "Loading... Please Wait 14",
    "Password Is Password 14",
    "LAN Solo 14",
    "It Hurts When IP 14",
    "Pretty Fly for a WiFi 14",
    "Nacho WiFi 14",
    "Tell My Router I Love Her 14",
    "404 WiFi Not Found 14",
    "The LAN Before Time 14",
    "Silence of the LANs 14",
    "Lord of the Pings 14",
    "Game of Phones 14",
    "Ping Me Maybe 14",
    "Wi Believe I Can Fi 14",
    "Keep Calm and Reboot 14",
    "Router? I Hardly Know Her 14",
    "No Free WiFi Here 14",
    "Buffering Forever 14",
    "Definitely A Microwave 14",
    "Ask Dad For Password 14",
    "Connecting Emotionally 14",
    "WiFi and Chill 14",
    "Unstable But Available 14",
    "This Is My Hotspot 14",
    "Yeet The Router 14",
    "Reboot and Pray 14",
    "Signal Lost Again 14",
    "Internet Went Outside 14",
    "Trust Me Im An Engineer 14",
    "Definitely Not Your Router 14",
    "LAN Me Alone 14",
    "Pretty Fly For A WiFi 14",
    "The Password Is Wrong 14",
    "Loading Personality 14",
    "404 Brain Not Found 14",
    "Low Battery High Hopes 14",
    "WiFi Has Left The Chat 14",
    "Router In Disguise 14",
    "Ping Pong Palace 14",
    "House of LAN 14",
    "May The WiFi Be With You 14",
    "One Does Not Simply Connect 14",
    "Winter Is Buffering 14",
    "You Shall Not Passcode 14",
    "The Ping Awakens 14",
    "Return of the WiFi 14",
    "Attack of the Clones 14",
    "Revenge of the Router 14",
    "A New LAN 14",
    "Mom Said No WiFi 15",
    "Definitely Not WiFi 15",
    "Loading... Please Wait 15",
    "Password Is Password 15",
    "LAN Solo 15",
    "It Hurts When IP 15",
    "Pretty Fly for a WiFi 15",
    "Nacho WiFi 15",
    "Tell My Router I Love Her 15",
    "404 WiFi Not Found 15",
    "The LAN Before Time 15",
    "Silence of the LANs 15",
    "Lord of the Pings 15",
    "Game of Phones 15",
    "Ping Me Maybe 15",
    "Wi Believe I Can Fi 15",
    "Keep Calm and Reboot 15",
    "Router? I Hardly Know Her 15",
    "No Free WiFi Here 15",
    "Buffering Forever 15",
    "Definitely A Microwave 15",
    "Ask Dad For Password 15",
    "Connecting Emotionally 15",
    "WiFi and Chill 15",
    "Unstable But Available 15",
    "This Is My Hotspot 15",
    "Yeet The Router 15",
    "Reboot and Pray 15",
    "Signal Lost Again 15",
    "Internet Went Outside 15",
    "Trust Me Im An Engineer 15",
    "Definitely Not Your Router 15",
    "LAN Me Alone 15",
    "Pretty Fly For A WiFi 15",
    "The Password Is Wrong 15",
    "Loading Personality 15",
    "404 Brain Not Found 15",
    "Low Battery High Hopes 15",
    "WiFi Has Left The Chat 15",
    "Router In Disguise 15",
    "Ping Pong Palace 15",
    "House of LAN 15",
    "May The WiFi Be With You 15",
    "One Does Not Simply Connect 15",
    "Winter Is Buffering 15",
    "You Shall Not Passcode 15",
    "The Ping Awakens 15",
    "Return of the WiFi 15",
    "Attack of the Clones 15",
    "Revenge of the Router 15",
    "A New LAN 15",
    "Mom Said No WiFi 16",
    "Definitely Not WiFi 16",
    "Loading... Please Wait 16",
    "Password Is Password 16",
    "LAN Solo 16",
    "It Hurts When IP 16",
    "Pretty Fly for a WiFi 16",
    "Nacho WiFi 16",
    "Tell My Router I Love Her 16",
    "404 WiFi Not Found 16",
    "The LAN Before Time 16",
    "Silence of the LANs 16",
    "Lord of the Pings 16",
    "Game of Phones 16",
    "Ping Me Maybe 16",
    "Wi Believe I Can Fi 16",
    "Keep Calm and Reboot 16",
    "Router? I Hardly Know Her 16",
    "No Free WiFi Here 16",
    "Buffering Forever 16",
    "Definitely A Microwave 16",
    "Ask Dad For Password 16",
    "Connecting Emotionally 16",
    "WiFi and Chill 16",
    "Unstable But Available 16",
    "This Is My Hotspot 16",
    "Yeet The Router 16",
    "Reboot and Pray 16",
    "Signal Lost Again 16",
    "Internet Went Outside 16",
    "Trust Me Im An Engineer 16",
    "Definitely Not Your Router 16",
    "LAN Me Alone 16",
    "Pretty Fly For A WiFi 16",
    "The Password Is Wrong 16",
    "Loading Personality 16",
    "404 Brain Not Found 16",
    "Low Battery High Hopes 16",
    "WiFi Has Left The Chat 16",
    "Router In Disguise 16",
    "Ping Pong Palace 16",
    "House of LAN 16",
    "May The WiFi Be With You 16",
    "One Does Not Simply Connect 16",
    "Winter Is Buffering 16",
    "You Shall Not Passcode 16",
    "The Ping Awakens 16",
    "Return of the WiFi 16",
    "Attack of the Clones 16",
    "Revenge of the Router 16",
    "A New LAN 16",
    "Mom Said No WiFi 17",
    "Definitely Not WiFi 17",
    "Loading... Please Wait 17",
    "Password Is Password 17",
    "LAN Solo 17",
    "It Hurts When IP 17",
    "Pretty Fly for a WiFi 17",
    "Nacho WiFi 17",
    "Tell My Router I Love Her 17",
    "404 WiFi Not Found 17",
    "The LAN Before Time 17",
    "Silence of the LANs 17",
    "Lord of the Pings 17",
    "Game of Phones 17",
    "Ping Me Maybe 17",
    "Wi Believe I Can Fi 17",
    "Keep Calm and Reboot 17",
    "Router? I Hardly Know Her 17",
    "No Free WiFi Here 17",
    "Buffering Forever 17",
    "Definitely A Microwave 17",
    "Ask Dad For Password 17",
    "Connecting Emotionally 17",
    "WiFi and Chill 17",
    "Unstable But Available 17",
    "This Is My Hotspot 17",
    "Yeet The Router 17",
    "Reboot and Pray 17",
    "Signal Lost Again 17",
    "Internet Went Outside 17",
    "Trust Me Im An Engineer 17",
    "Definitely Not Your Router 17",
    "LAN Me Alone 17",
    "Pretty Fly For A WiFi 17",
    "The Password Is Wrong 17",
    "Loading Personality 17",
    "404 Brain Not Found 17",
    "Low Battery High Hopes 17",
    "WiFi Has Left The Chat 17",
    "Router In Disguise 17",
    "Ping Pong Palace 17",
    "House of LAN 17",
    "May The WiFi Be With You 17",
    "One Does Not Simply Connect 17",
    "Winter Is Buffering 17",
    "You Shall Not Passcode 17",
    "The Ping Awakens 17",
    "Return of the WiFi 17",
    "Attack of the Clones 17",
    "Revenge of the Router 17",
    "A New LAN 17",
    "Mom Said No WiFi 18",
    "Definitely Not WiFi 18",
    "Loading... Please Wait 18",
    "Password Is Password 18",
    "LAN Solo 18",
    "It Hurts When IP 18",
    "Pretty Fly for a WiFi 18",
    "Nacho WiFi 18",
    "Tell My Router I Love Her 18",
    "404 WiFi Not Found 18",
    "The LAN Before Time 18",
    "Silence of the LANs 18",
    "Lord of the Pings 18",
    "Game of Phones 18",
    "Ping Me Maybe 18",
    "Wi Believe I Can Fi 18",
    "Keep Calm and Reboot 18",
    "Router? I Hardly Know Her 18",
    "No Free WiFi Here 18",
    "Buffering Forever 18",
    "Definitely A Microwave 18",
    "Ask Dad For Password 18",
    "Connecting Emotionally 18",
    "WiFi and Chill 18",
    "Unstable But Available 18",
    "This Is My Hotspot 18",
    "Yeet The Router 18",
    "Reboot and Pray 18",
    "Signal Lost Again 18",
    "Internet Went Outside 18",
    "Trust Me Im An Engineer 18",
    "Definitely Not Your Router 18",
    "LAN Me Alone 18",
    "Pretty Fly For A WiFi 18",
    "The Password Is Wrong 18",
    "Loading Personality 18",
    "404 Brain Not Found 18",
    "Low Battery High Hopes 18",
    "WiFi Has Left The Chat 18",
    "Router In Disguise 18",
    "Ping Pong Palace 18",
    "House of LAN 18",
    "May The WiFi Be With You 18",
    "One Does Not Simply Connect 18",
    "Winter Is Buffering 18",
    "You Shall Not Passcode 18",
    "The Ping Awakens 18",
    "Return of the WiFi 18",
    "Attack of the Clones 18",
    "Revenge of the Router 18",
    "A New LAN 18",
    "Mom Said No WiFi 19",
    "Definitely Not WiFi 19",
    "Loading... Please Wait 19",
    "Password Is Password 19",
    "LAN Solo 19",
    "It Hurts When IP 19",
    "Pretty Fly for a WiFi 19",
    "Nacho WiFi 19",
    "Tell My Router I Love Her 19",
    "404 WiFi Not Found 19",
    "The LAN Before Time 19",
    "Silence of the LANs 19",
    "Lord of the Pings 19",
    "Game of Phones 19",
    "Ping Me Maybe 19",
    "Wi Believe I Can Fi 19",
    "Keep Calm and Reboot 19",
    "Router? I Hardly Know Her 19",
    "No Free WiFi Here 19",
    "Buffering Forever 19",
    "Definitely A Microwave 19",
    "Ask Dad For Password 19",
    "Connecting Emotionally 19",
    "WiFi and Chill 19",
    "Unstable But Available 19",
    "This Is My Hotspot 19",
    "Yeet The Router 19",
    "Reboot and Pray 19",
    "Signal Lost Again 19",
    "Internet Went Outside 19",
    "Trust Me Im An Engineer 19",
    "Definitely Not Your Router 19",
    "LAN Me Alone 19",
    "Pretty Fly For A WiFi 19",
    "The Password Is Wrong 19",
    "Loading Personality 19",
    "404 Brain Not Found 19",
    "Low Battery High Hopes 19",
    "WiFi Has Left The Chat 19",
    "Router In Disguise 19",
    "Ping Pong Palace 19",
    "House of LAN 19",
    "May The WiFi Be With You 19",
    "One Does Not Simply Connect 19",
    "Winter Is Buffering 19",
    "You Shall Not Passcode 19",
    "The Ping Awakens 19",
    "Return of the WiFi 19",
    "Attack of the Clones 19",
    "Revenge of the Router 19",
    "A New LAN 19",
    "Mom Said No WiFi 20",
    "Definitely Not WiFi 20",
    "Loading... Please Wait 20",
    "Password Is Password 20",
    "LAN Solo 20",
    "It Hurts When IP 20",
    "Pretty Fly for a WiFi 20",
    "Nacho WiFi 20",
    "Tell My Router I Love Her 20",
    "404 WiFi Not Found 20",
    "The LAN Before Time 20",
    "Silence of the LANs 20",
    "Lord of the Pings 20",
    "Game of Phones 20",
    "Ping Me Maybe 20",
    "Wi Believe I Can Fi 20",
    "Keep Calm and Reboot 20",
    "Router? I Hardly Know Her 20",
    "No Free WiFi Here 20",
    "Buffering Forever 20",
    "Definitely A Microwave 20",
    "Ask Dad For Password 20",
    "Connecting Emotionally 20",
    "WiFi and Chill 20",
    "Unstable But Available 20",
    "This Is My Hotspot 20",
    "Yeet The Router 20",
    "Reboot and Pray 20",
    "Signal Lost Again 20",
    "Internet Went Outside 20",
    "Trust Me Im An Engineer 20"
};

const size_t FAKE_SSID_COUNT = sizeof(fakeSSIDs) / sizeof(fakeSSIDs[0]);


// ================== CONFIG ==================
#define BUTTON_PIN 0  // Boot button on standard ESP32 boards (active LOW)
#define LED_PIN    2  // Onboard LED GPIO pin

uint8_t packet[200];
int packetLen = 0;
int ssidLenOffset = 0;
int ssidDataOffset = 0;
int channelOffset = 0;

int currentChannel = 1;
const int numSSIDs = sizeof(fakeSSIDs) / sizeof(fakeSSIDs[0]);

void initBeaconTemplate();
void sendBeacon(const char* ssid);

void setup() {
  Serial.begin(115200);
  delay(1000);
  pinMode(LED_PIN, OUTPUT);

  setCpuFrequencyMhz(240);
  // Clean start
  esp_wifi_stop();
  delay(100);
  WiFi.mode(WIFI_MODE_NULL);
  delay(100);

  WiFi.mode(WIFI_MODE_STA);
  esp_wifi_set_promiscuous(true);
  delay(200);

  initBeaconTemplate();

  uint8_t mac[6];

  unsigned long pressStartTime = 0;
  
  while (true) {
    // The boot button is active-LOW (reads LOW when pressed)
    if (digitalRead(BUTTON_PIN) == LOW) {
      if (pressStartTime == 0) {
        pressStartTime = millis(); // Start the timer on initial press
      } else if (millis() - pressStartTime >= 2000) {
        break; // Exit the setup block's blocking loop
      }
    } else {
      // Reset timer if the button is released prematurely
      pressStartTime = 0;
    }
    
    delay(20); // Prevent watchdog trigger and debounce slightly
  }

  // Turn LED on once the button check passes
  digitalWrite(LED_PIN, HIGH);
}

void loop() {
  for (int i = 0; i < numSSIDs; i++) {
    sendBeacon(fakeSSIDs[i]);
  }
}

void sendBeacon(const char* ssid) {
  esp_wifi_set_channel(currentChannel, WIFI_SECOND_CHAN_NONE);

  // Randomize Source MAC and BSSID at offset 10
    uint8_t mac[6];
    for (int i = 0; i < 6; i++) mac[i] = random(0, 256);
    memcpy(&packet[10], mac, 6);     // Source
    memcpy(&packet[16], mac, 6);     // BSSID

    // Update Channel
    packet[channelOffset] = currentChannel;

    // Update SSID Length and String data
    int ssidLen = strlen(ssid); 
    
    packet[ssidLenOffset] = ssidLen;
    memcpy(&packet[ssidDataOffset], ssid, ssidLen);

    // Compute final size and transmit instantly
    int currentSize = ssidDataOffset + ssidLen + 15; 
    esp_wifi_80211_tx(WIFI_IF_STA, packet, currentSize, false);
  
  //Channel switching logic
  currentChannel++;  
  if (currentChannel > 11) {
    currentChannel = 1;
  }
}

// 2. Run this ONCE in setup() to build the fixed template
void initBeaconTemplate() {
    int offset = 0;
    
    packet[offset++] = 0x80;  // Management, Beacon
    packet[offset++] = 0x00;
    packet[offset++] = 0x00;  // Duration
    packet[offset++] = 0x00;

    // Destination = broadcast
    for (int i = 0; i < 6; i++) packet[offset++] = 0xFF;

    // Skip Source MAC + BSSID (12 bytes total) - patched live
    offset += 12; 

    packet[offset++] = 0x00;  // Sequence control low
    packet[offset++] = 0x00;

    // Timestamp
    for (int i = 0; i < 8; i++) packet[offset++] = 0x00;

    packet[offset++] = 0x64;  // Beacon interval low
    packet[offset++] = 0x00;  // high

    packet[offset++] = 0x01;  // Capability low (open)
    packet[offset++] = 0x04;  // high

    // === SSID IE Placeholder ===
    packet[offset++] = 0x00;  // Element ID: SSID
    ssidLenOffset = offset++; // Save position for length byte
    ssidDataOffset = offset;  // Save position where string starts
    
    offset += 32;             // Reserve max 32 bytes for SSID space

    // Supported Rates (Static)
    packet[offset++] = 0x01;
    packet[offset++] = 0x08;
    const uint8_t rates[8] = {0x82, 0x84, 0x8b, 0x96, 0x12, 0x24, 0x48, 0x6c};
    memcpy(&packet[offset], rates, 8);
    offset += 8;

    // Channel IE Placeholder
    packet[offset++] = 0x03;
    packet[offset++] = 0x01;
    channelOffset = offset;   // Save position to update channel live
    packet[offset++] = 1;     

    // Extended Supported Rates (Static)
    packet[offset++] = 0x32;
    packet[offset++] = 0x04;
    const uint8_t ext_rates[4] = {0x0c, 0x18, 0x30, 0x60};
    memcpy(&packet[offset], ext_rates, 4);
    offset += 4;

    packetLen = offset;       // Baseline length
}